# Generated by Django 4.1.6 on 2023-02-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_app", "0004_alter_relationship_options"),
        ("posts_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="liked",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to="profiles_app.profile"
            ),
        ),
    ]
