# Generated by Django 4.1.6 on 2023-02-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_app", "0003_alter_relationship_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relationship",
            options={"ordering": ["created"]},
        ),
    ]
